import { GameThemeConfig } from './theme.model';

export const FOODS_THEME: GameThemeConfig = {
  id: 'foods',
  symbolPool: [
    { key: 'symbol-01', frontImage: '/assets/gamethemes/food/Property 1=Component 3.png', frontFilter: null },
    { key: 'symbol-02', frontImage: '/assets/gamethemes/food/Property 1=Component 3 (1).png', frontFilter: null },
    { key: 'symbol-03', frontImage: '/assets/gamethemes/food/Property 1=Component 3 (2).png', frontFilter: null },
    { key: 'symbol-04', frontImage: '/assets/gamethemes/food/Property 1=Component 3 (3).png', frontFilter: null },
    { key: 'symbol-05', frontImage: '/assets/gamethemes/food/Property 1=Component 3 (4).png', frontFilter: null },
    { key: 'symbol-06', frontImage: '/assets/gamethemes/food/Property 1=Component 3 (5).png', frontFilter: null },
    { key: 'symbol-07', frontImage: '/assets/gamethemes/food/Property 1=Component 3 (6).png', frontFilter: null },
    { key: 'symbol-08', frontImage: '/assets/gamethemes/food/Property 1=Component 3 (7).png', frontFilter: null },
    { key: 'symbol-09', frontImage: '/assets/gamethemes/food/Property 1=Component 3 (8).png', frontFilter: null },
    { key: 'symbol-10', frontImage: '/assets/gamethemes/food/Property 1=Component 3 (9).png', frontFilter: null },
    { key: 'symbol-11', frontImage: '/assets/gamethemes/food/Property 1=Component 3 (10).png', frontFilter: null },
    { key: 'symbol-12', frontImage: '/assets/gamethemes/food/Property 1=Component 3 (11).png', frontFilter: null },
    { key: 'symbol-13', frontImage: '/assets/gamethemes/food/Property 1=Component 3 (12).png', frontFilter: null },
    { key: 'symbol-14', frontImage: '/assets/gamethemes/food/Property 1=Component 3 (13).png', frontFilter: null },
    { key: 'symbol-15', frontImage: '/assets/gamethemes/food/Property 1=Component 3 (14).png', frontFilter: null },
    { key: 'symbol-16', frontImage: '/assets/gamethemes/food/Property 1=Component 3 (15).png', frontFilter: null },
    { key: 'symbol-17', frontImage: '/assets/gamethemes/food/Property 1=Component 3 (16).png', frontFilter: null },
    { key: 'symbol-18', frontImage: '/assets/gamethemes/food/Property 1=Component 3 (2).png', frontFilter: 'hue-rotate(28deg) saturate(1.2)' },
  ],
  assets: {
    backImage: '/assets/gamethemes/food/hidden.png',
    bluePlayerImage: '/assets/gamethemes/gamestheme/blue.png',
    orangePlayerImage: '/assets/gamethemes/gamestheme/orange.png',
    whitePlayerImage: '/assets/gamethemes/gamestheme/white.png',
    exitButtonImage: '/assets/gamethemes/food/exit.png',
    exitButtonHoverImage: '/assets/gamethemes/food/exithover.png',
    backButtonImage: '/assets/gamethemes/food/back.png',
    backButtonHoverImage: '/assets/gamethemes/food/backhover.png',
    yesQuitButtonImage: '/assets/gamethemes/food/exit.png',
    yesQuitButtonHoverImage: '/assets/gamethemes/food/exithover.png',
    confettiImage: '/assets/gamethemes/codevibe/confetti.png',
    trophyImage: '/assets/gamethemes/pockal%201.png',
  },
  usesWhiteCurrentPlayerSymbol: false,
  header: {
    currentPlayerBadgeClass: {
      blue: 'player-indicator-badge',
      orange: 'player-indicator-badge',
    },
  },
  result: {
    winnerTitles: {
      blue: 'Blue Player',
      orange: 'Orange Player',
      draw: 'Draw',
    },
    winnerSymbols: {
      blue: '/assets/gamethemes/winnerblue.png',
      orange: '/assets/gamethemes/winnerorange.png',
      draw: null,
    },
    winnerSymbolClass: 'winner-symbol winner-symbol--foods',
    winnerBackButtonLabel: 'Home',
    gameOverBlueScoreImage: '/assets/gamethemes/gamestheme/blue.png',
    gameOverOrangeScoreImage: '/assets/gamethemes/gamestheme/orange.png',
    gameOverLabelImage: null,
    showConfetti: false,
  },
};
