import { GameThemeConfig } from './theme.model';

export const DA_PROJECTS_THEME: GameThemeConfig = {
  id: 'da-projects',
  symbolPool: [
    { key: 'symbol-01', frontImage: '/assets/gamethemes/daprojects/Property 1=Component 2.png', frontFilter: null },
    { key: 'symbol-02', frontImage: '/assets/gamethemes/daprojects/Property 1=Component 2 (1).png', frontFilter: null },
    { key: 'symbol-03', frontImage: '/assets/gamethemes/daprojects/Property 1=Component 2 (2).png', frontFilter: null },
    { key: 'symbol-04', frontImage: '/assets/gamethemes/daprojects/Property 1=Component 2 (3).png', frontFilter: null },
    { key: 'symbol-05', frontImage: '/assets/gamethemes/daprojects/Property 1=Component 2 (4).png', frontFilter: null },
    { key: 'symbol-06', frontImage: '/assets/gamethemes/daprojects/Property 1=Component 2 (5).png', frontFilter: null },
    { key: 'symbol-07', frontImage: '/assets/gamethemes/daprojects/Property 1=Component 2 (6).png', frontFilter: null },
    { key: 'symbol-08', frontImage: '/assets/gamethemes/daprojects/Property 1=Component 2 (7).png', frontFilter: null },
    { key: 'symbol-09', frontImage: '/assets/gamethemes/daprojects/Property 1=Component 2 (8).png', frontFilter: null },
    { key: 'symbol-10', frontImage: '/assets/gamethemes/daprojects/Property 1=Component 2 (9).png', frontFilter: null },
    { key: 'symbol-11', frontImage: '/assets/gamethemes/daprojects/Property 1=Component 2 (10).png', frontFilter: null },
    { key: 'symbol-12', frontImage: '/assets/gamethemes/daprojects/Property 1=Component 2 (11).png', frontFilter: null },
    { key: 'symbol-13', frontImage: '/assets/gamethemes/daprojects/Property 1=Component 2 (12).png', frontFilter: null },
    { key: 'symbol-14', frontImage: '/assets/gamethemes/daprojects/Property 1=Component 2 (13).png', frontFilter: null },
    { key: 'symbol-15', frontImage: '/assets/gamethemes/daprojects/Property 1=Component 2 (14).png', frontFilter: null },
    { key: 'symbol-16', frontImage: '/assets/gamethemes/daprojects/Property 1=Component 2 (15).png', frontFilter: null },
    { key: 'symbol-17', frontImage: '/assets/gamethemes/daprojects/Property 1=Component 2 (16).png', frontFilter: null },
    { key: 'symbol-18', frontImage: '/assets/gamethemes/daprojects/Property 1=Component 2 (1).png', frontFilter: 'hue-rotate(140deg) saturate(1.2)' },
  ],
  assets: {
    backImage: '/assets/gamethemes/daprojects/Frame 727.png',
    bluePlayerImage: '/assets/gamethemes/gamestheme/blue.png',
    orangePlayerImage: '/assets/gamethemes/gamestheme/orange.png',
    whitePlayerImage: '/assets/gamethemes/gamestheme/white.png',
    exitButtonImage: '/assets/gamethemes/daprojects/exit.png',
    exitButtonHoverImage: '/assets/gamethemes/daprojects/exithover.png',
    backButtonImage: '/assets/gamethemes/daprojects/back.png',
    backButtonHoverImage: '/assets/gamethemes/daprojects/backhover.png',
    yesQuitButtonImage: '/assets/gamethemes/daprojects/bye.png',
    yesQuitButtonHoverImage: '/assets/gamethemes/daprojects/byehover.png',
    confettiImage: '/assets/gamethemes/codevibe/confetti.png',
    trophyImage: '/assets/gamethemes/pockal%201.png',
  },
  usesWhiteCurrentPlayerSymbol: false,
  header: {
    currentPlayerBadgeClass: {
      blue: 'player-indicator-badge',
      orange: 'player-indicator-badge',
    },
  },
  result: {
    winnerTitles: {
      blue: 'Blue Player',
      orange: 'Orange Player',
      draw: 'Draw',
    },
    winnerSymbols: {
      blue: '/assets/gamethemes/winblueborder.png',
      orange: '/assets/gamethemes/winorangeborder.png',
      draw: null,
    },
    winnerSymbolClass: 'winner-symbol winner-symbol--da-projects',
    winnerBackButtonLabel: 'Back to start',
    gameOverBlueScoreImage: '/assets/gamethemes/gamestheme/blue.png',
    gameOverOrangeScoreImage: '/assets/gamethemes/gamestheme/orange.png',
    gameOverLabelImage: '/assets/gamethemes/daprojects/label (1).png',
    showConfetti: false,
  },
};
