import { GameThemeConfig } from './theme.model';

export const CODE_VIBES_THEME: GameThemeConfig = {
  id: 'code-vibes',
  symbolPool: [
    { key: 'symbol-01', frontImage: '/assets/gamethemes/codevibe/cards/Property 1=Component 22.png', frontFilter: null },
    { key: 'symbol-02', frontImage: '/assets/gamethemes/codevibe/cards/Property 1=Component 22 (1).png', frontFilter: null },
    { key: 'symbol-03', frontImage: '/assets/gamethemes/codevibe/cards/Property 1=Component 22 (2).png', frontFilter: null },
    { key: 'symbol-04', frontImage: '/assets/gamethemes/codevibe/cards/Property 1=Component 22 (3).png', frontFilter: null },
    { key: 'symbol-05', frontImage: '/assets/gamethemes/codevibe/cards/Property 1=Component 22 (4).png', frontFilter: null },
    { key: 'symbol-06', frontImage: '/assets/gamethemes/codevibe/cards/Property 1=Component 22 (5).png', frontFilter: null },
    { key: 'symbol-07', frontImage: '/assets/gamethemes/codevibe/cards/Property 1=Component 22 (6).png', frontFilter: null },
    { key: 'symbol-08', frontImage: '/assets/gamethemes/codevibe/cards/Property 1=Component 22 (7).png', frontFilter: null },
    { key: 'symbol-09', frontImage: '/assets/gamethemes/codevibe/cards/Property 1=Component 22 (8).png', frontFilter: null },
    { key: 'symbol-10', frontImage: '/assets/gamethemes/codevibe/cards/Property 1=Component 22 (9).png', frontFilter: null },
    { key: 'symbol-11', frontImage: '/assets/gamethemes/codevibe/cards/Property 1=Component 22 (10).png', frontFilter: null },
    { key: 'symbol-12', frontImage: '/assets/gamethemes/codevibe/cards/Property 1=Component 22 (11).png', frontFilter: null },
    { key: 'symbol-13', frontImage: '/assets/gamethemes/codevibe/cards/Property 1=Component 22 (12).png', frontFilter: null },
    { key: 'symbol-14', frontImage: '/assets/gamethemes/codevibe/cards/Property 1=Component 22 (13).png', frontFilter: null },
    { key: 'symbol-15', frontImage: '/assets/gamethemes/codevibe/cards/Property 1=Component 22 (14).png', frontFilter: null },
    { key: 'symbol-16', frontImage: '/assets/gamethemes/codevibe/cards/Front.png', frontFilter: null },
    { key: 'symbol-17', frontImage: '/assets/gamethemes/codevibe/cards/Property 1=Component 22 (1).png', frontFilter: 'hue-rotate(115deg) saturate(1.2)' },
    { key: 'symbol-18', frontImage: '/assets/gamethemes/codevibe/cards/Property 1=Component 22 (2).png', frontFilter: 'hue-rotate(245deg) saturate(1.15)' },
  ],
  assets: {
    backImage: '/assets/gamethemes/codevibe/cards/hidden.png',
    bluePlayerImage: '/assets/gamethemes/codevibe/blue.png',
    orangePlayerImage: '/assets/gamethemes/codevibe/orange.png',
    whitePlayerImage: '/assets/gamethemes/gamestheme/white.png',
    exitButtonImage: '/assets/gamethemes/codevibe/exit.png',
    exitButtonHoverImage: null,
    backButtonImage: '/assets/gamethemes/codevibe/back.png',
    backButtonHoverImage: null,
    yesQuitButtonImage: null,
    yesQuitButtonHoverImage: null,
    confettiImage: '/assets/gamethemes/codevibe/confetti.png',
    trophyImage: '/assets/gamethemes/pockal%201.png',
  },
  usesWhiteCurrentPlayerSymbol: false,
  header: {
    currentPlayerBadgeClass: {
      blue: 'player-indicator-badge',
      orange: 'player-indicator-badge',
    },
  },
  result: {
    winnerTitles: {
      blue: 'BLUE PLAYER',
      orange: 'ORANGE PLAYER',
      draw: "IT'S A DRAW",
    },
    winnerSymbols: {
      blue: '/assets/gamethemes/winnerblue.png',
      orange: '/assets/gamethemes/winnerorange.png',
      draw: null,
    },
    winnerSymbolClass: 'winner-symbol',
    winnerBackButtonLabel: 'Back to start',
    gameOverBlueScoreImage: null,
    gameOverOrangeScoreImage: null,
    gameOverLabelImage: null,
    showConfetti: true,
  },
};
