import { GameThemeConfig } from './theme.model';

export const GAMING_THEME: GameThemeConfig = {
  id: 'gaming',
  symbolPool: [
    { key: 'symbol-01', frontImage: '/assets/gamethemes/gamestheme/Property 1=Component 2 (1).png', frontFilter: null },
    { key: 'symbol-02', frontImage: '/assets/gamethemes/gamestheme/Property 1=Component 2 (2).png', frontFilter: null },
    { key: 'symbol-03', frontImage: '/assets/gamethemes/gamestheme/Property 1=Component 2 (3).png', frontFilter: null },
    { key: 'symbol-04', frontImage: '/assets/gamethemes/gamestheme/Property 1=Component 2 (4).png', frontFilter: null },
    { key: 'symbol-05', frontImage: '/assets/gamethemes/gamestheme/Property 1=Component 2 (5).png', frontFilter: null },
    { key: 'symbol-06', frontImage: '/assets/gamethemes/gamestheme/Property 1=Component 2 (6).png', frontFilter: null },
    { key: 'symbol-07', frontImage: '/assets/gamethemes/gamestheme/Property 1=Component 2 (8).png', frontFilter: null },
    { key: 'symbol-08', frontImage: '/assets/gamethemes/gamestheme/Property 1=Component 2 (9).png', frontFilter: null },
    { key: 'symbol-09', frontImage: '/assets/gamethemes/gamestheme/Property 1=Component 2 (10).png', frontFilter: null },
    { key: 'symbol-10', frontImage: '/assets/gamethemes/gamestheme/Property 1=Component 2 (11).png', frontFilter: null },
    { key: 'symbol-11', frontImage: '/assets/gamethemes/gamestheme/Property 1=Component 2 (12).png', frontFilter: null },
    { key: 'symbol-12', frontImage: '/assets/gamethemes/gamestheme/Property 1=Component 2 (13).png', frontFilter: null },
    { key: 'symbol-13', frontImage: '/assets/gamethemes/gamestheme/Property 1=Component 2 (14).png', frontFilter: null },
    { key: 'symbol-14', frontImage: '/assets/gamethemes/gamestheme/Property 1=Component 2 (15).png', frontFilter: null },
    { key: 'symbol-15', frontImage: '/assets/gamethemes/gamestheme/Property 1=Component 2 (16).png', frontFilter: null },
    { key: 'symbol-16', frontImage: '/assets/gamethemes/gamestheme/Front.png', frontFilter: null },
    { key: 'symbol-17', frontImage: '/assets/gamethemes/gamestheme/circle.png', frontFilter: null },
    { key: 'symbol-18', frontImage: '/assets/gamethemes/gamestheme/Property 1=Component 2 (1).png', frontFilter: 'hue-rotate(145deg) saturate(1.15)' },
  ],
  assets: {
    backImage: '/assets/gamethemes/gamestheme/hiddengame.png',
    bluePlayerImage: '/assets/gamethemes/gamestheme/blue.png',
    orangePlayerImage: '/assets/gamethemes/gamestheme/orange.png',
    whitePlayerImage: '/assets/gamethemes/gamestheme/white.png',
    exitButtonImage: '/assets/gamethemes/gamestheme/exit.png',
    exitButtonHoverImage: null,
    backButtonImage: '/assets/gamethemes/gamestheme/back.png',
    backButtonHoverImage: '/assets/gamethemes/gamestheme/backhover.png',
    yesQuitButtonImage: '/assets/gamethemes/gamestheme/yesquitthegame.png',
    yesQuitButtonHoverImage: null,
    confettiImage: '/assets/gamethemes/codevibe/confetti.png',
    trophyImage: '/assets/gamethemes/pockal%201.png',
  },
  usesWhiteCurrentPlayerSymbol: true,
  header: {
    currentPlayerBadgeClass: {
      blue: 'player-indicator-badge player-indicator-badge--blue',
      orange: 'player-indicator-badge player-indicator-badge--orange',
    },
  },
  result: {
    winnerTitles: {
      blue: 'Blue Player',
      orange: 'Orange Player',
      draw: 'Draw',
    },
    winnerSymbols: {
      blue: '/assets/gamethemes/pockal%201.png',
      orange: '/assets/gamethemes/pockal%201.png',
      draw: '/assets/gamethemes/pockal%201.png',
    },
    winnerSymbolClass: 'winner-symbol winner-symbol--gaming',
    winnerBackButtonLabel: 'Home',
    gameOverBlueScoreImage: '/assets/gamethemes/gamestheme/blue.png',
    gameOverOrangeScoreImage: '/assets/gamethemes/gamestheme/orange.png',
    gameOverLabelImage: null,
    showConfetti: false,
  },
};
